[package]
name = "hc-daemon"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hc-core.workspace = true
hc-sign.workspace = true

alloy-primitives.workspace = true
df-share.workspace = true
err_mac.workspace = true
hex.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
k256.workspace = true
libc.workspace = true
parking_lot.workspace = true
qrcode.workspace = true
pki-types.workspace = true
rand.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde_json.workspace = true
solana-keypair.workspace = true
solana-signer.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
hc-core = { workspace = true, features = ["test-util"] }
hc-sign = { workspace = true, features = ["test-util"] }
sha2.workspace = true
ureq.workspace = true
