//! Secure Enclave P-256 KEK: a Touch-ID-gated key whose ECDH unwraps the DEK.
//!
//! The private key is generated by CryptoKit's `SecureEnclave.P256.KeyAgreement`
//! (Swift shim in `swift/se_bridge.swift`), never leaves the enclave, and persists as
//! an opaque `dataRepresentation` blob in a 0600 file under the home dir — no keychain,
//! no entitlement, no provisioning profile. Each ECDH requires a live biometric.
//!
//! A blob carries its own access-control policy, and any process running as this user can mint
//! an enclave key with no policy at all. So the blob file existing proves nothing: a key is
//! adopted only when its public key is already recorded as this install's — `se_pub` in
//! `keyring.json` for the KEK, `grant_public_key` in `config.toml` for the grant key. An
//! unrecorded blob is refused outright rather than adopted or overwritten.
//!
//! [`ensure_se_key`] and [`ensure_grant_key`] hand that check's result back as a
//! [`ProvenEnclaveKey`], and every caller wraps, pins and records THAT value. One read of the
//! blob path backs both the check and the use, so a blob swapped in afterwards cannot become the
//! key a DEK is wrapped under.
//!
//! Refusing forever would leave the same process able to brick the enclave path by squatting the
//! blob path, so [`unrecorded_se_key`] and [`unrecorded_grant_key`] name what is there against
//! what this install records and hand back an [`UnrecordedEnclaveKeyBlob`], whose
//! [`UnrecordedEnclaveKeyBlob::discard`] removes it for [`DISCARD_UNRECORDED_KEY_PHRASE`] and
//! nothing else. A key this install DOES record is never a candidate: that one is the operator's,
//! and deleting it costs them the enclave path.
//!
//! Enrollment computes `ECDH(eph_priv, se_pub)` on the host (`p256`); unlock computes the
//! mirror `ECDH(se_priv, eph_pub)` in the enclave. Standard P-256 ECDH is symmetric and
//! both sides encode the raw big-endian X-coordinate (32 bytes, no KDF), so they must
//! yield identical bytes. `hot_cheese se-selftest` proves that on real hardware.
//!
//! Alongside the KEK sits a second, independent enclave key: the **grant key**
//! (`SecureEnclave.P256.Signing`, blob `se_grant_<label>.blob`). It wraps nothing and
//! decrypts nothing. Its only job is [`grant_sign`]: a biometric-gated ECDSA signature over
//! SHA-256 of a caller-supplied message, so a signature under the pinned public key is
//! hardware-attested proof that a human approved exactly those bytes. Losing it costs
//! nothing but a re-run of `hot_cheese enroll grant`.
use crate::crypto::envelope::write_private_file_new;
use crate::keyring::{EnrollParams, Keyring, KeyringErr};
use crate::mac::local_auth::LaContext;
use err_mac::create_err_with_impls;
use std::ffi::{c_char, c_void, CString};
use std::path::{Path, PathBuf};
use zeroize::Zeroizing;

create_err_with_impls!(
    #[derive(Debug)]
    pub SeErr,
    Unavailable,
    ScreenLocked,
    KeyNotFound,
    BadPubKeyLen(usize),
    BadPeerPoint,
    SoftwareKey,
    TouchIdDenied,
    Ecdh,
    GrantSign,
    GrantSignatureInvalid,
    BadBlob,
    BufferTooSmall,
    Shim(i32),
    StdIo(std::io::Error),
    Config(crate::config::ConfigErr),
    Keyring(KeyringErr),
    Hex(hex::FromHexError)
    ;
    Create { code: i32 },
    AccessControl { code: i32 },
    BadSignatureLen { len: usize },
    GrantReuseWindowExceeded { elapsed_ms: u64, window_ms: u64 },
    InvalidLabel { label: String },
    UnrecordedEnclaveKeyAtKeyPath { path: PathBuf, found: String, recorded: Vec<String> },
    EnclaveKeyPathOccupied { path: PathBuf },
    BlobNotOwnerOnly { path: PathBuf },
    BlobNotAKeyFile { path: PathBuf },
    NoEnclaveKeyToDiscard { path: PathBuf },
    RecordedEnclaveKeyNotDiscardable { path: PathBuf, se_key: String },
    EnclaveKeyChangedUnderDiscard { path: PathBuf, shown: String, found: String },
    DiscardNotConfirmed { required: &'static str },
);

/// What an operator types to remove an enclave key this install never recorded, and the only
/// thing [`UnrecordedEnclaveKeyBlob::discard`] acts on.
pub const DISCARD_UNRECORDED_KEY_PHRASE: &str = "discard this unrecorded hot_cheese enclave key";

/// Raw P-256 ECDH result: the 32-byte field element (X-coordinate).
const P256_SHARED_LEN: usize = 32;
/// Uncompressed SEC1 point: `0x04 || X(32) || Y(32)`.
const SEC1_UNCOMPRESSED_LEN: usize = 65;
const SEC1_UNCOMPRESSED_TAG: u8 = 0x04;
/// Raw P-256 ECDSA signature: `r(32) || s(32)`, no DER wrapper.
const P256_SIGNATURE_LEN: usize = 64;
/// Upper bound for a `SecureEnclave.P256` `dataRepresentation` blob (~569 bytes observed).
const SE_BLOB_MAX: usize = 1024;

/// `errSecInteractionNotAllowed`: the SEP will not issue a `kSecAttrAccessibleWhenUnlocked`
/// key while the login session's screen is locked.
const ERR_SEC_INTERACTION_NOT_ALLOWED: i32 = -25308;

const HC_ERR_CREATE: i32 = -1;
const HC_ERR_ACCESS_CONTROL: i32 = -2;
const HC_ERR_BAD_BLOB: i32 = -3;
const HC_ERR_BAD_PEER: i32 = -4;
const HC_ERR_ECDH: i32 = -5;
const HC_ERR_SIGN: i32 = -6;
const HC_ERR_BUFFER_TOO_SMALL: i32 = -10;

/// The label under which every machine stores its device-bound Secure Enclave KEK key.
/// Shared by the CLI and the SSH bootstrap so they always reference the same key.
pub const SE_KEY_LABEL: &str = "hotcheese.se.kek.v1";

/// The label under which every machine stores its device-bound Secure Enclave grant key.
pub const SE_GRANT_KEY_LABEL: &str = "hotcheese.se.grant.v1";

/// Touch ID sheet text for the two throwaway-key ECDHs of [`selftest`].
const SELFTEST_REASON: &str = "Run the hot_cheese Secure Enclave self-test";

/// Touch ID sheet text for the single pre-evaluated context [`selftest`] reuses.
const SELFTEST_REUSE_REASON: &str =
    "Approve once for the hot_cheese Secure Enclave self-test (ECDH + grant signature)";

/// Payload [`selftest`] signs with the throwaway grant key and verifies host-side.
const SELFTEST_GRANT_MSG: &[u8] = b"hotcheese/se-grant-selftest/v1";

extern "C" {
    fn hc_se_available() -> i32;
    fn hc_se_create(out: *mut u8, cap: usize, out_len: *mut usize, detail: *mut i32) -> i32;
    fn hc_se_public_key(
        blob: *const u8,
        blob_len: usize,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_ecdh(
        blob: *const u8,
        blob_len: usize,
        peer: *const u8,
        peer_len: usize,
        la_ctx: *mut c_void,
        reason: *const c_char,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_sign_create(out: *mut u8, cap: usize, out_len: *mut usize, detail: *mut i32) -> i32;
    fn hc_se_sign_public_key(
        blob: *const u8,
        blob_len: usize,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_sign_grant(
        blob: *const u8,
        blob_len: usize,
        msg: *const u8,
        msg_len: usize,
        la_ctx: *mut c_void,
        reason: *const c_char,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
}

fn map_shim(code: i32) -> SeErr {
    match code {
        HC_ERR_BAD_BLOB => SeErr::BadBlob,
        HC_ERR_BAD_PEER => SeErr::BadPeerPoint,
        HC_ERR_ECDH => SeErr::Ecdh,
        HC_ERR_SIGN => SeErr::GrantSign,
        HC_ERR_BUFFER_TOO_SMALL => SeErr::BufferTooSmall,
        other => SeErr::Shim(other),
    }
}

/// Whether this machine has a usable Secure Enclave.
pub fn se_available() -> bool {
    unsafe { hc_se_available() == 1 }
}

/// Refuse labels whose on-disk spelling would be ambiguous. Within this alphabet replacing a
/// dot with `_` is injective because an input underscore is not legal; the byte ceiling also
/// keeps every derived filename comfortably within one filesystem component.
fn validate_label(label: &str) -> Result<(), SeErr> {
    let valid = !label.is_empty()
        && label.len() <= crate::MAX_NAME_BYTES
        && label
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'.');
    if valid {
        Ok(())
    } else {
        Err(SeErr::InvalidLabel {
            label: crate::safe_diagnostic_text(label),
        })
    }
}

/// Map a validated key label to a filesystem-safe stem shared by the SE-blob and demo-key schemes.
fn sanitize_label(label: &str) -> String {
    label
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// On-disk location of the Secure Enclave key blob for `label` (under the home dir).
fn se_blob_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("se_kek_{}.blob", sanitize_label(label)))
}

/// On-disk location of the Secure Enclave grant-signing key blob for `label`.
fn se_grant_blob_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("se_grant_{}.blob", sanitize_label(label)))
}

/// Read the key blob at `path`. Only an absent file is [`SeErr::KeyNotFound`]; a file that is
/// there but is not this user's bounded 0600 regular file keeps its own variant, because "your
/// key is gone, fall back to the passphrase" and "something else is squatting on your key path"
/// call for opposite responses from the operator.
fn read_blob(path: &Path) -> Result<Zeroizing<Vec<u8>>, SeErr> {
    match crate::read_private_file_bounded(path, SE_BLOB_MAX as u64) {
        Ok(bytes) => Ok(bytes),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Err(SeErr::KeyNotFound),
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            Err(SeErr::BlobNotOwnerOnly {
                path: path.to_path_buf(),
            })
        }
        Err(e) if e.kind() == std::io::ErrorKind::InvalidData => Err(SeErr::BlobNotAKeyFile {
            path: path.to_path_buf(),
        }),
        Err(e) => Err(e.into()),
    }
}

/// The `se_pub` of every Secure Enclave enrollment this install has recorded — the only public
/// keys a KEK blob may present. A store with no `keyring.json` yet has recorded none.
fn enrolled_se_public_keys() -> Result<Vec<Vec<u8>>, SeErr> {
    let config = crate::config::Config::load()?;
    let keyring = match Keyring::load(&crate::mac::MacBackend::keyring_path(&config.store)) {
        Ok(keyring) => keyring,
        Err(KeyringErr::StdIo(e)) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(Vec::new())
        }
        Err(e) => return Err(e.into()),
    };
    let mut enrolled = Vec::new();
    for enrollment in &keyring.enrollments {
        if let EnrollParams::SecureEnclave { se_pub, .. } = &enrollment.params {
            enrolled.push(se_pub.clone());
        }
    }
    Ok(enrolled)
}

/// The grant public key pinned in `config.toml` — the only one a grant blob may present.
fn pinned_grant_public_key() -> Result<Vec<Vec<u8>>, SeErr> {
    let Some(pinned) = crate::config::Config::load()?.grant_public_key else {
        return Ok(Vec::new());
    };
    Ok(vec![hex::decode(pinned)?])
}

/// The 16 lowercase hex characters of SHA-256 over a SEC1 enclave public key: the one form every
/// surface names an enclave key by, so an operator can compare what `list` shows with what a
/// refusal reports.
pub fn se_fingerprint(public_key: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    hex::encode(&Sha256::digest(public_key)[..8])
}

/// An enclave public key this install has proven is its own, returned by the check so the
/// caller records the key that was checked instead of re-reading the blob path.
#[derive(Debug)]
#[must_use]
pub struct ProvenEnclaveKey {
    /// Uncompressed SEC1 point (`0x04 || X || Y`) of the proven key.
    public_key: Vec<u8>,
}

impl ProvenEnclaveKey {
    pub fn public_key(&self) -> &[u8] {
        &self.public_key
    }
}

/// Ensure this machine's Touch-ID-bound SE KEK under `label` exists and return its proven public
/// key. A blob already at the path is adopted only when `keyring.json` records its public key.
/// No Touch ID.
pub fn ensure_se_key(label: &str) -> Result<ProvenEnclaveKey, SeErr> {
    validate_label(label)?;
    let (path, ops) = kek_at(label);
    ensure_enclave_key_at(&path, &enrolled_se_public_keys()?, ops)
}

/// Shim entry point that mints an enclave key and writes its `dataRepresentation`.
type ShimCreate = unsafe extern "C" fn(*mut u8, usize, *mut usize, *mut i32) -> i32;
/// Shim entry point that reloads a blob and writes the key's SEC1 public point.
type ShimPublicKey = unsafe extern "C" fn(*const u8, usize, *mut u8, usize, *mut usize) -> i32;

/// The two path-level operations one kind of enclave key supports.
#[derive(Clone, Copy, Debug)]
struct EnclaveKeyOps {
    /// Mints a fresh key at the path and returns its SEC1 public key, failing with
    /// `AlreadyExists` when the path is occupied.
    mint: fn(&Path) -> Result<Vec<u8>, SeErr>,
    /// Reads the SEC1 public key of whatever key blob is at the path. No Touch ID.
    public_key: fn(&Path) -> Result<Vec<u8>, SeErr>,
}

const SE_KEK_OPS: EnclaveKeyOps = EnclaveKeyOps {
    mint: |path| create_blob_at(path, hc_se_create, hc_se_public_key),
    public_key: |path| export_public_key(path, hc_se_public_key),
};

const SE_GRANT_OPS: EnclaveKeyOps = EnclaveKeyOps {
    mint: |path| create_blob_at(path, hc_se_sign_create, hc_se_sign_public_key),
    public_key: |path| export_public_key(path, hc_se_sign_public_key),
};

const SOFTWARE_OPS: EnclaveKeyOps = EnclaveKeyOps {
    mint: mint_software_key,
    public_key: software_pubkey,
};

fn checked_ffi_output(out: &[u8], out_len: usize) -> Result<&[u8], SeErr> {
    if out_len == 0 {
        return Err(SeErr::BadBlob);
    }
    out.get(..out_len).ok_or(SeErr::BufferTooSmall)
}

/// Mint an enclave key through `create`, persist its blob 0600 at `path`, and return the public
/// key of the bytes just written — derived from those same bytes, never re-read. No Touch ID.
fn create_blob_at(
    path: &Path,
    create: ShimCreate,
    export: ShimPublicKey,
) -> Result<Vec<u8>, SeErr> {
    if !se_available() {
        return Err(SeErr::Unavailable);
    }
    let mut out = Zeroizing::new([0u8; SE_BLOB_MAX]);
    let mut out_len: usize = 0;
    let mut detail: i32 = 0;
    let code = unsafe { create(out.as_mut_ptr(), out.len(), &mut out_len, &mut detail) };
    match code {
        0 => {}
        HC_ERR_CREATE if detail == ERR_SEC_INTERACTION_NOT_ALLOWED => {
            return Err(SeErr::ScreenLocked)
        }
        HC_ERR_CREATE => return Err(SeErr::Create { code: detail }),
        HC_ERR_ACCESS_CONTROL => return Err(SeErr::AccessControl { code: detail }),
        other => return Err(map_shim(other)),
    }
    let blob = checked_ffi_output(out.as_ref(), out_len)?;
    write_private_file_new(path, blob)?;
    public_key_of_blob(blob, export)
}

/// Take the key blob at `path` as this machine's, minting one only while the path is free. A
/// blob already there is adopted ONLY when its public key is one of `recorded`: an enclave key's
/// access-control policy travels inside its blob, so an unrecorded blob is an unproven key that
/// may have been minted with no biometric gate at all. No Touch ID.
fn ensure_enclave_key_at(
    path: &Path,
    recorded: &[Vec<u8>],
    ops: EnclaveKeyOps,
) -> Result<ProvenEnclaveKey, SeErr> {
    match (ops.public_key)(path) {
        Ok(present) => {
            if recorded.iter().any(|known| known == &present) {
                return Ok(ProvenEnclaveKey {
                    public_key: present,
                });
            }
            let found = se_fingerprint(&present);
            let recorded: Vec<String> =
                recorded.iter().map(|known| se_fingerprint(known)).collect();
            tracing::error!(
                path = %path.display(),
                %found,
                ?recorded,
                "an enclave key this install never recorded is sitting at the key path; refusing \
                 to adopt it as this machine's key. Compare `found` with the `se_key` of every \
                 enrollment; do not remove that file on this refusal alone"
            );
            return Err(SeErr::UnrecordedEnclaveKeyAtKeyPath {
                path: path.to_path_buf(),
                found,
                recorded,
            });
        }
        Err(SeErr::KeyNotFound) => {}
        Err(e) => return Err(e),
    }
    let minted = match (ops.mint)(path) {
        Ok(public_key) => public_key,
        Err(SeErr::StdIo(e)) if e.kind() == std::io::ErrorKind::AlreadyExists => {
            return Err(SeErr::EnclaveKeyPathOccupied {
                path: path.to_path_buf(),
            })
        }
        Err(e) => return Err(e),
    };
    tracing::info!(path = %path.display(), "minted this machine's enclave key");
    Ok(ProvenEnclaveKey { public_key: minted })
}

/// Where `label`'s KEK lives and how it is read: the enclave blob, or the demo software key when
/// that backend is on.
fn kek_at(label: &str) -> (PathBuf, EnclaveKeyOps) {
    if software_enclave_enabled() {
        return (software_key_path(label), SOFTWARE_OPS);
    }
    (se_blob_path(label), SE_KEK_OPS)
}

/// Where `label`'s grant key lives and how it is read.
fn grant_at(label: &str) -> (PathBuf, EnclaveKeyOps) {
    if software_enclave_enabled() {
        return (software_grant_key_path(label), SOFTWARE_OPS);
    }
    (se_grant_blob_path(label), SE_GRANT_OPS)
}

/// Export the SE public key as uncompressed SEC1 (`0x04 || X || Y`, 65 bytes). No Touch ID.
pub fn se_public_key(label: &str) -> Result<Vec<u8>, SeErr> {
    validate_label(label)?;
    let (path, ops) = kek_at(label);
    (ops.public_key)(&path)
}

/// Reload the blob at `path` through `export` and return its 65-byte uncompressed SEC1
/// public point, rejecting anything that is not one. No Touch ID.
fn export_public_key(path: &Path, export: ShimPublicKey) -> Result<Vec<u8>, SeErr> {
    public_key_of_blob(&read_blob(path)?, export)
}

/// The 65-byte uncompressed SEC1 public point of the key `blob` holds, through `export`,
/// rejecting anything that is not one. No Touch ID.
fn public_key_of_blob(blob: &[u8], export: ShimPublicKey) -> Result<Vec<u8>, SeErr> {
    let mut out = [0u8; SEC1_UNCOMPRESSED_LEN];
    let mut out_len: usize = 0;
    let code = unsafe {
        export(
            blob.as_ptr(),
            blob.len(),
            out.as_mut_ptr(),
            out.len(),
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != SEC1_UNCOMPRESSED_LEN || out[0] != SEC1_UNCOMPRESSED_TAG {
        return Err(SeErr::BadPubKeyLen(out_len));
    }
    Ok(out.to_vec())
}

/// Deterministic ECDH between the SE private key and `peer_pub_sec1` (65-byte SEC1).
/// Triggers Touch ID (reusing `auth`'s pre-evaluated context when present, which already
/// carries its own prompt text). `reason` names the key and operation on the Touch ID sheet
/// of a fresh prompt. Returns the 32-byte shared X-coordinate, zeroized on drop.
pub fn se_ecdh(
    label: &str,
    peer_pub_sec1: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<Zeroizing<[u8; 32]>, SeErr> {
    validate_label(label)?;
    if software_enclave_enabled() {
        return software_se_ecdh(label, peer_pub_sec1, auth, reason);
    }
    if peer_pub_sec1.len() != SEC1_UNCOMPRESSED_LEN || peer_pub_sec1[0] != SEC1_UNCOMPRESSED_TAG {
        return Err(SeErr::BadPubKeyLen(peer_pub_sec1.len()));
    }
    if p256::PublicKey::from_sec1_bytes(peer_pub_sec1).is_err() {
        return Err(SeErr::BadPeerPoint);
    }
    let blob = read_blob(&se_blob_path(label))?;
    let la_ctx = match auth {
        Some(a) => a.as_raw_ptr(),
        None => std::ptr::null_mut(),
    };
    let reason_c = CString::new(reason).map_err(|_| SeErr::TouchIdDenied)?;
    let mut out = Zeroizing::new([0u8; P256_SHARED_LEN]);
    let mut out_len: usize = 0;
    let code = unsafe {
        hc_se_ecdh(
            blob.as_ptr(),
            blob.len(),
            peer_pub_sec1.as_ptr(),
            peer_pub_sec1.len(),
            la_ctx,
            reason_c.as_ptr(),
            out.as_mut_ptr(),
            P256_SHARED_LEN,
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != P256_SHARED_LEN {
        return Err(SeErr::Ecdh);
    }
    Ok(out)
}

/// Ensure this machine's Touch-ID-bound SE grant-signing key under `label` exists and return its
/// proven public key. A blob already at the path is adopted only when `config.toml` pins its
/// public key. Wraps nothing and unwraps nothing, so losing it costs only a re-run. No Touch ID.
pub fn ensure_grant_key(label: &str) -> Result<ProvenEnclaveKey, SeErr> {
    validate_label(label)?;
    let (path, ops) = grant_at(label);
    ensure_enclave_key_at(&path, &pinned_grant_public_key()?, ops)
}

/// Export the grant key's public key as uncompressed SEC1 (65 bytes). No Touch ID.
pub fn grant_public_key(label: &str) -> Result<Vec<u8>, SeErr> {
    validate_label(label)?;
    let (path, ops) = grant_at(label);
    (ops.public_key)(&path)
}

/// ECDSA-sign SHA-256 of `msg` inside the enclave and return the raw `r || s` (64 bytes).
/// Triggers Touch ID (reusing `auth`'s pre-evaluated context when present); `reason` names
/// the operation on the sheet of a fresh prompt. The signature is public: it is proof that a
/// live human approved exactly `msg`, never a secret.
pub fn grant_sign(
    label: &str,
    msg: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<[u8; P256_SIGNATURE_LEN], SeErr> {
    validate_label(label)?;
    if software_enclave_enabled() {
        return software_grant_sign(label, msg, auth, reason);
    }
    let blob = read_blob(&se_grant_blob_path(label))?;
    let la_ctx = match auth {
        Some(a) => a.as_raw_ptr(),
        None => std::ptr::null_mut(),
    };
    let reason_c = CString::new(reason).map_err(|_| SeErr::TouchIdDenied)?;
    let mut out = [0u8; P256_SIGNATURE_LEN];
    let mut out_len: usize = 0;
    let code = unsafe {
        hc_se_sign_grant(
            blob.as_ptr(),
            blob.len(),
            msg.as_ptr(),
            msg.len(),
            la_ctx,
            reason_c.as_ptr(),
            out.as_mut_ptr(),
            P256_SIGNATURE_LEN,
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != P256_SIGNATURE_LEN {
        return Err(SeErr::BadSignatureLen { len: out_len });
    }
    Ok(out)
}

/// Remove the key blob at `path`. Idempotent, and final: the blob is an enclave key's only
/// persistence, so removing it makes that key unrecoverable.
fn remove_enclave_key(path: &Path) -> Result<(), SeErr> {
    match std::fs::remove_file(path) {
        Ok(()) => {
            tracing::warn!(path = %path.display(), "removed an enclave key blob");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}

/// A key blob squatting this machine's enclave key path whose public key no record of this
/// install names, carried with the ops that read it so a discard re-reads the same path the same
/// way. Constructible only by [`unrecorded_key_at`], which is what makes "unrecorded" a property
/// of the value rather than a claim its holder makes.
#[derive(Debug)]
#[must_use]
pub struct UnrecordedEnclaveKeyBlob {
    /// The blob file a discard would remove.
    path: PathBuf,
    /// Uncompressed SEC1 public key of the key sitting there, which nothing recorded names.
    found: Vec<u8>,
    /// Every enclave public key this install records for this kind of key.
    recorded: Vec<Vec<u8>>,
    /// How that path is read, so the discard identifies the key the same way the check did.
    ops: EnclaveKeyOps,
}

impl UnrecordedEnclaveKeyBlob {
    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn found(&self) -> &[u8] {
        &self.found
    }

    pub fn recorded(&self) -> &[Vec<u8>] {
        &self.recorded
    }

    /// Remove the blob, for [`DISCARD_UNRECORDED_KEY_PHRASE`] and nothing else. The key at the
    /// path is identified again first: a same-uid process that swaps the operator's own key in
    /// between the question and the answer must not have this delete it for them.
    pub fn discard(self, typed: &str) -> Result<(), SeErr> {
        if typed.trim() != DISCARD_UNRECORDED_KEY_PHRASE {
            return Err(SeErr::DiscardNotConfirmed {
                required: DISCARD_UNRECORDED_KEY_PHRASE,
            });
        }
        let present = (self.ops.public_key)(&self.path)?;
        if present != self.found {
            return Err(SeErr::EnclaveKeyChangedUnderDiscard {
                path: self.path,
                shown: se_fingerprint(&self.found),
                found: se_fingerprint(&present),
            });
        }
        remove_enclave_key(&self.path)
    }
}

/// The key blob at `path` when it is one `recorded` does not name — the only kind a discard may
/// remove. A key this install records is the operator's own, so it is refused outright rather
/// than offered; an empty path has nothing to discard.
fn unrecorded_key_at(
    path: PathBuf,
    recorded: Vec<Vec<u8>>,
    ops: EnclaveKeyOps,
) -> Result<UnrecordedEnclaveKeyBlob, SeErr> {
    let found = match (ops.public_key)(&path) {
        Ok(found) => found,
        Err(SeErr::KeyNotFound) => return Err(SeErr::NoEnclaveKeyToDiscard { path }),
        Err(e) => return Err(e),
    };
    if recorded.iter().any(|known| known == &found) {
        return Err(SeErr::RecordedEnclaveKeyNotDiscardable {
            se_key: se_fingerprint(&found),
            path,
        });
    }
    Ok(UnrecordedEnclaveKeyBlob {
        path,
        found,
        recorded,
        ops,
    })
}

/// The KEK blob squatting this machine's key path, when `keyring.json` records no enrollment
/// under its public key. Reads only; nothing is removed until [`UnrecordedEnclaveKeyBlob::discard`].
pub fn unrecorded_se_key(label: &str) -> Result<UnrecordedEnclaveKeyBlob, SeErr> {
    validate_label(label)?;
    let (path, ops) = kek_at(label);
    unrecorded_key_at(path, enrolled_se_public_keys()?, ops)
}

/// The grant-key blob squatting this machine's grant path, when `config.toml` pins a different
/// public key (or none). Reads only.
pub fn unrecorded_grant_key(label: &str) -> Result<UnrecordedEnclaveKeyBlob, SeErr> {
    validate_label(label)?;
    let (path, ops) = grant_at(label);
    unrecorded_key_at(path, pinned_grant_public_key()?, ops)
}

/// True only when the insecure software-enclave demo backend is explicitly enabled. It
/// swaps the Secure Enclave for an extractable on-disk P-256 key gated by a Touch ID
/// prompt, reproducing the exact enroll/unlock/serve flow. NEVER for real keys.
pub fn software_enclave_enabled() -> bool {
    std::env::var("HOT_CHEESE_INSECURE_SOFTWARE_ENCLAVE").as_deref() == Ok("1")
}

/// On-disk location of the demo software key for `label`. Per-label so the throwaway
/// self-test key never shares a file with (and deletes) the real enrolled key.
fn software_key_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("software_enclave_{}.key", sanitize_label(label)))
}

/// On-disk location of the demo software GRANT key for `label`. Distinct from the demo KEK
/// file so the demo keeps the same two-independent-keys shape as the hardware path.
fn software_grant_key_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("software_grant_{}.key", sanitize_label(label)))
}

/// Mint the demo software key at `path`, 0600 and create-exclusive like the enclave blob, and
/// return the public key of the scalar just written.
fn mint_software_key(path: &Path) -> Result<Vec<u8>, SeErr> {
    let sk = p256::SecretKey::random(&mut rand::rngs::OsRng);
    let raw = Zeroizing::new(sk.to_bytes());
    write_private_file_new(path, &raw)?;
    tracing::warn!(
        path = %path.display(),
        "DEMO: created a SOFTWARE 'enclave' key ON DISK (extractable, NOT hardware-backed)"
    );
    Ok(sk.public_key().to_sec1_bytes().into_vec())
}

/// Load the demo software key (32-byte P-256 scalar) from `path`. A missing file reads as
/// [`SeErr::KeyNotFound`], exactly as a missing enclave blob does, so the demo shows the
/// hardware path's "not enrolled" failures rather than a raw io error.
fn load_software_key_at(path: &Path) -> Result<p256::SecretKey, SeErr> {
    let bytes = read_blob(path)?;
    if bytes.len() != P256_SHARED_LEN {
        return Err(SeErr::SoftwareKey);
    }
    let field = p256::FieldBytes::clone_from_slice(&bytes);
    p256::SecretKey::from_bytes(&field).map_err(|_| SeErr::SoftwareKey)
}

/// Demo public key as uncompressed SEC1 (65 bytes).
fn software_pubkey(path: &Path) -> Result<Vec<u8>, SeErr> {
    let sk = load_software_key_at(path)?;
    Ok(sk.public_key().to_sec1_bytes().into_vec())
}

/// Demo ECDH: gate with a real Touch ID prompt (LAContext) carrying `reason`, then ECDH
/// against the software key. Same deterministic raw shared secret as the SE path.
fn software_se_ecdh(
    label: &str,
    peer_pub_sec1: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<Zeroizing<[u8; 32]>, SeErr> {
    tracing::warn!("DEMO software enclave: unlocking with an on-disk key (NOT hardware)");
    if auth.is_none()
        && !crate::mac::authorize_with_touch_id(&format!("{reason} (DEMO software enclave)"))
    {
        return Err(SeErr::TouchIdDenied);
    }
    let sk = load_software_key_at(&software_key_path(label))?;
    let peer = p256::PublicKey::from_sec1_bytes(peer_pub_sec1).map_err(|_| SeErr::BadPeerPoint)?;
    let shared = p256::ecdh::diffie_hellman(sk.to_nonzero_scalar(), peer.as_affine());
    let mut out = [0u8; 32];
    out.copy_from_slice(shared.raw_secret_bytes().as_slice());
    Ok(Zeroizing::new(out))
}

/// Demo grant signature: gate with a real Touch ID prompt carrying `reason`, then ECDSA-sign
/// SHA-256 of `msg` host-side. Same 64-byte `r || s` shape the enclave returns.
fn software_grant_sign(
    label: &str,
    msg: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<[u8; P256_SIGNATURE_LEN], SeErr> {
    use p256::ecdsa::signature::Signer;

    tracing::warn!("DEMO software enclave: signing a grant with an on-disk key (NOT hardware)");
    if auth.is_none()
        && !crate::mac::authorize_with_touch_id(&format!("{reason} (DEMO software enclave)"))
    {
        return Err(SeErr::TouchIdDenied);
    }
    let sk = load_software_key_at(&software_grant_key_path(label))?;
    let signing = p256::ecdsa::SigningKey::from(&sk);
    let signature: p256::ecdsa::Signature = signing.sign(msg);
    let mut out = [0u8; P256_SIGNATURE_LEN];
    out.copy_from_slice(&signature.to_bytes());
    Ok(out)
}

/// Validate the Secure Enclave path end-to-end (requires SE hardware + Touch ID): create
/// throwaway KEK and grant keys under `label`, confirm the enclave ECDH against their proven
/// public keys is deterministic AND equals the host-side p256 ECDH used at enrollment, then
/// confirm that ONE pre-evaluated `LAContext` covers BOTH an enclave ECDH and an enclave ECDSA
/// grant signature that verifies host-side — the property per-payload grants are built on.
/// Returns the first failed property; both throwaway keys are deleted either way. Prompts Touch
/// ID three times: once per fresh ECDH, then once for the reused context. `label` MUST NOT be a
/// real deployment key.
pub fn selftest(label: &str) -> Result<(), SeErr> {
    use p256::ecdh::EphemeralSecret;
    use p256::ecdsa::signature::Verifier;
    use p256::elliptic_curve::sec1::ToEncodedPoint;
    use rand::rngs::OsRng;

    validate_label(label)?;
    let (kek_path, kek_ops) = kek_at(label);
    let (grant_path, grant_ops) = grant_at(label);
    remove_enclave_key(&kek_path)?;
    remove_enclave_key(&grant_path)?;
    let kek = ensure_enclave_key_at(&kek_path, &[], kek_ops)?;
    let grant = ensure_enclave_key_at(&grant_path, &[], grant_ops)?;

    let result = (|| {
        let pk = kek.public_key();
        let eph = EphemeralSecret::random(&mut OsRng);
        let eph_pub = eph.public_key().to_encoded_point(false);
        let s1 = se_ecdh(label, eph_pub.as_bytes(), None, SELFTEST_REASON)?;
        let s2 = se_ecdh(label, eph_pub.as_bytes(), None, SELFTEST_REASON)?;
        if s1.as_slice() != s2.as_slice() {
            tracing::error!("SE ECDH is non-deterministic for a fixed peer");
            return Err(SeErr::Ecdh);
        }
        let se_pub = p256::PublicKey::from_sec1_bytes(pk).map_err(|_| SeErr::BadPeerPoint)?;
        let host_shared = eph.diffie_hellman(&se_pub);
        if s1.as_slice() != host_shared.raw_secret_bytes().as_slice() {
            tracing::error!(
                "SE ECDH(se_priv, eph_pub) != host ECDH(eph_priv, se_pub) — SE-wrapped DEKs \
                 would be unrecoverable"
            );
            return Err(SeErr::Ecdh);
        }

        let grant_pk = grant.public_key();
        let verifying = p256::ecdsa::VerifyingKey::from_sec1_bytes(grant_pk)
            .map_err(|_| SeErr::BadPubKeyLen(grant_pk.len()))?;
        let auth = LaContext::evaluate_biometric(SELFTEST_REUSE_REASON)?;
        let started = std::time::Instant::now();
        let reused = se_ecdh(label, eph_pub.as_bytes(), Some(&auth), SELFTEST_REASON)?;
        let raw = grant_sign(label, SELFTEST_GRANT_MSG, Some(&auth), SELFTEST_REASON)?;
        let elapsed_ms = started.elapsed().as_millis() as u64;

        if reused.as_slice() != s1.as_slice() {
            tracing::error!(
                "SE ECDH under the reused context differs from the freshly prompted one"
            );
            return Err(SeErr::Ecdh);
        }
        let signature =
            p256::ecdsa::Signature::from_slice(&raw).map_err(|_| SeErr::GrantSignatureInvalid)?;
        if verifying.verify(SELFTEST_GRANT_MSG, &signature).is_err() {
            tracing::error!(
                "enclave grant signature does not verify under the exported grant public key — \
                 an approval could never be proven"
            );
            return Err(SeErr::GrantSignatureInvalid);
        }
        let window_ms = (crate::mac::local_auth::TOUCH_ID_REUSE_SECS * 1000.0) as u64;
        if elapsed_ms > window_ms {
            tracing::error!(
                elapsed_ms,
                window_ms,
                "the enclave ECDH + grant signature did not both land inside the Touch ID reuse \
                 window, so one biometric per payload is NOT proven"
            );
            return Err(SeErr::GrantReuseWindowExceeded {
                elapsed_ms,
                window_ms,
            });
        }
        tracing::info!(
            elapsed_ms,
            window_ms,
            "one biometric covered both the enclave ECDH and the enclave grant signature"
        );
        Ok(())
    })();

    let _ = remove_enclave_key(&kek_path);
    let _ = remove_enclave_key(&grant_path);
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    #[test]
    fn ffi_create_length_is_checked_before_slicing_the_output_buffer() {
        assert!(matches!(
            checked_ffi_output(&[0u8; 8], 9),
            Err(SeErr::BufferTooSmall)
        ));
        assert!(matches!(
            checked_ffi_output(&[0u8; 8], 0),
            Err(SeErr::BadBlob)
        ));
        assert_eq!(
            checked_ffi_output(&[1u8; 8], 3).expect("in bounds"),
            &[1u8; 3]
        );
    }

    /// Proves the FFI create/persist/reload path and the adoption gate on real SE hardware
    /// without a Touch ID prompt, skipping when the SEP refuses because the screen is locked.
    #[test]
    fn se_key_creates_persists_and_exports_pubkey_without_touch_id() {
        if !se_available() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("hc_se_smoke_{}", std::process::id()));
        let path = dir.join("se_kek_smoke.blob");
        let _ = std::fs::remove_file(&path);

        let minted = match ensure_enclave_key_at(&path, &[], SE_KEK_OPS) {
            Err(SeErr::ScreenLocked) => return,
            other => other.expect("create SE key blob"),
        };
        assert!(path.exists(), "blob file must be written");
        let mode = std::fs::metadata(&path)
            .expect("stat blob")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "blob must be 0600");

        let pk = export_public_key(&path, hc_se_public_key).expect("export public key");
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        assert_eq!(
            minted.public_key(),
            pk,
            "the key minted at the path must be the key reloaded from it"
        );

        assert!(
            matches!(
                ensure_enclave_key_at(&path, &[], SE_KEK_OPS),
                Err(SeErr::UnrecordedEnclaveKeyAtKeyPath { .. })
            ),
            "an enclave key no enrollment records must not be adopted"
        );
        let adopted = ensure_enclave_key_at(&path, std::slice::from_ref(&pk), SE_KEK_OPS)
            .expect("a recorded enclave key is adopted");
        assert_eq!(adopted.public_key(), pk);

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }

    /// Proves the grant key's create/persist/reload FFI path on real SE hardware without a
    /// Touch ID prompt, skipping when the SEP refuses because the screen is locked.
    #[test]
    fn grant_key_creates_persists_and_exports_pubkey_without_touch_id() {
        if !se_available() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("hc_grant_smoke_{}", std::process::id()));
        let path = dir.join("se_grant_smoke.blob");
        let _ = std::fs::remove_file(&path);

        let minted = match create_blob_at(&path, hc_se_sign_create, hc_se_sign_public_key) {
            Err(SeErr::ScreenLocked) => return,
            other => other.expect("create SE grant key blob"),
        };
        assert!(path.exists(), "blob file must be written");
        let mode = std::fs::metadata(&path)
            .expect("stat blob")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "blob must be 0600");

        let pk = export_public_key(&path, hc_se_sign_public_key).expect("export public key");
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        assert_eq!(
            minted, pk,
            "the key minted at the path must be the key reloaded from it"
        );

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }

    /// The DEMO software-enclave FILE backend persists, reloads identically, and exports the
    /// 65-byte uncompressed SEC1 public key that enroll/unlock depend on.
    #[test]
    fn software_demo_key_persists_and_exports_uncompressed_pubkey() {
        let path = std::env::temp_dir().join(format!("hc_sw_se_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);
        mint_software_key(&path).expect("create");
        let sk1 = load_software_key_at(&path).expect("load");
        let sk2 = load_software_key_at(&path).expect("reload");
        assert_eq!(
            sk1.to_bytes(),
            sk2.to_bytes(),
            "persisted key must be stable"
        );
        let pk = sk1.public_key().to_sec1_bytes().into_vec();
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        let _ = std::fs::remove_file(&path);
    }

    /// A key blob planted at the key path is only ever adopted when its public key is one this
    /// install already recorded: an unrecorded one is refused outright, and the refusal neither
    /// re-mints over the blob nor leaves the caller a key it has not proven is biometry-gated.
    #[test]
    fn an_unrecorded_key_blob_is_refused_rather_than_adopted_or_overwritten() {
        let path = std::env::temp_dir().join(format!("hc_planted_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);

        let minted =
            ensure_enclave_key_at(&path, &[], SOFTWARE_OPS).expect("mint while the path is free");
        let planted = std::fs::read(&path).expect("read the key that is now at the path");
        let planted_pub = software_pubkey(&path).expect("public key of the planted key");
        assert_eq!(minted.public_key(), planted_pub);

        let refusal = ensure_enclave_key_at(&path, &[], SOFTWARE_OPS);
        assert!(
            matches!(
                &refusal,
                Err(SeErr::UnrecordedEnclaveKeyAtKeyPath { found, recorded, .. })
                    if *found == se_fingerprint(&planted_pub) && recorded.is_empty()
            ),
            "{refusal:?}"
        );
        assert_eq!(
            std::fs::read(&path).expect("blob survives the refusal"),
            planted,
            "a refusal must not re-mint over the key that is there"
        );

        let unrelated = p256::SecretKey::random(&mut rand::rngs::OsRng)
            .public_key()
            .to_sec1_bytes()
            .into_vec();
        let refusal = ensure_enclave_key_at(&path, std::slice::from_ref(&unrelated), SOFTWARE_OPS);
        assert!(
            matches!(
                &refusal,
                Err(SeErr::UnrecordedEnclaveKeyAtKeyPath { found, recorded, .. })
                    if *found == se_fingerprint(&planted_pub)
                        && *recorded == [se_fingerprint(&unrelated)]
            ),
            "the refusal must name the squatter next to the key this install records: {refusal:?}"
        );

        let adopted = ensure_enclave_key_at(&path, &[unrelated, planted_pub.clone()], SOFTWARE_OPS)
            .expect("a recorded key is adopted");
        assert_eq!(adopted.public_key(), planted_pub);
        assert_eq!(
            std::fs::read(&path).expect("blob survives adoption"),
            planted
        );
        let _ = std::fs::remove_file(&path);
    }

    /// The enrollment a proof feeds records the key that was proven, so a blob a same-uid process
    /// swaps in between the check and the wrap never becomes the key the DEK is wrapped under.
    #[test]
    fn an_enrollment_records_the_proven_key_not_a_blob_swapped_in_after_the_proof() {
        use crate::crypto::envelope::Dek;
        use crate::keyring::EnrollParams;

        let path = std::env::temp_dir().join(format!("hc_swapped_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);

        let proven =
            ensure_enclave_key_at(&path, &[], SOFTWARE_OPS).expect("mint while the path is free");
        let proven_pub = proven.public_key().to_vec();

        let squatter = p256::SecretKey::random(&mut rand::rngs::OsRng);
        std::fs::write(&path, squatter.to_bytes()).expect("swap the blob under the proof");
        let squatter_pub = squatter.public_key().to_sec1_bytes().into_vec();
        assert_ne!(proven_pub, squatter_pub);
        assert_eq!(
            software_pubkey(&path).expect("read the swapped blob"),
            squatter_pub,
            "the key path must really hold the swapped key by now"
        );

        let enrollment = crate::unlock::enroll_secure_enclave("swapped", &Dek::random(), &proven)
            .expect("enroll");
        let EnrollParams::SecureEnclave { se_pub, .. } = &enrollment.params else {
            panic!("a Secure Enclave enrollment must carry SecureEnclave params");
        };
        assert_eq!(
            se_pub, &proven_pub,
            "the DEK must be wrapped under the proven key, not the one now at the path"
        );
        let _ = std::fs::remove_file(&path);
    }

    /// Full SE round-trip (create, pubkey, deterministic + host-equivalent ECDH, one-biometric
    /// ECDH + grant signature, delete) via `selftest`, the same check `hot_cheese se-selftest`
    /// runs.
    #[test]
    #[ignore = "requires Secure Enclave hardware + Touch ID (prompts biometrics)"]
    fn se_key_lifecycle_and_deterministic_ecdh() {
        const TEST_LABEL: &str = "hotcheese.se.test.key";
        selftest(TEST_LABEL).expect("SE self-test");
        assert!(matches!(se_public_key(TEST_LABEL), Err(SeErr::KeyNotFound)));
        assert!(matches!(
            grant_public_key(TEST_LABEL),
            Err(SeErr::KeyNotFound)
        ));
    }

    /// The discard exists for a squatted blob, so the one thing it must never reach is a key this
    /// install records: that key is the operator's own, and removing it costs them the enclave
    /// path. The refusal names it by the same fingerprint `list` prints, and leaves the file.
    #[test]
    fn a_recorded_enclave_key_is_never_a_discard_candidate() {
        let path = std::env::temp_dir().join(format!("hc_recorded_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);

        let mine = ensure_enclave_key_at(&path, &[], SOFTWARE_OPS).expect("mint at a free path");
        let mine_pub = mine.public_key().to_vec();
        let blob = std::fs::read(&path).expect("read the minted key");

        let refusal = unrecorded_key_at(path.clone(), vec![mine_pub.clone()], SOFTWARE_OPS);
        assert!(
            matches!(
                &refusal,
                Err(SeErr::RecordedEnclaveKeyNotDiscardable { se_key, .. })
                    if *se_key == se_fingerprint(&mine_pub)
            ),
            "{refusal:?}"
        );
        assert_eq!(
            std::fs::read(&path).expect("the recorded key survives the refusal"),
            blob
        );

        let unrelated = p256::SecretKey::random(&mut rand::rngs::OsRng)
            .public_key()
            .to_sec1_bytes()
            .into_vec();
        assert!(
            unrecorded_key_at(
                path.clone(),
                vec![unrelated, mine_pub.clone()],
                SOFTWARE_OPS
            )
            .is_err(),
            "one recorded match among several is still the operator's own key"
        );
        assert!(std::fs::metadata(&path).is_ok());
        let _ = std::fs::remove_file(&path);
    }

    /// The unrecorded blob is the safe case, but it is still a delete: only the exact phrase
    /// spends it, and the key is identified again at that moment, so a same-uid process that
    /// swaps the operator's own key in between the question and the answer cannot get this to
    /// remove it for them.
    #[test]
    fn an_unrecorded_enclave_key_is_discarded_only_for_the_exact_phrase() {
        let path = std::env::temp_dir().join(format!("hc_discard_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);

        let mine = p256::SecretKey::random(&mut rand::rngs::OsRng);
        let mine_pub = mine.public_key().to_sec1_bytes().into_vec();
        let squatter =
            ensure_enclave_key_at(&path, &[], SOFTWARE_OPS).expect("plant at a free path");
        let squatter_pub = squatter.public_key().to_vec();

        let found = unrecorded_key_at(path.clone(), vec![mine_pub.clone()], SOFTWARE_OPS)
            .expect("a key no record names is a discard candidate");
        assert_eq!(found.path(), path);
        assert_eq!(found.found(), squatter_pub);
        assert_eq!(found.recorded(), std::slice::from_ref(&mine_pub));
        assert_eq!(se_fingerprint(found.found()).len(), 16);

        let refused = found.discard("y");
        assert!(
            matches!(refused, Err(SeErr::DiscardNotConfirmed { .. })),
            "{refused:?}"
        );
        assert!(
            std::fs::metadata(&path).is_ok(),
            "a refused confirmation must delete nothing"
        );

        let found = unrecorded_key_at(path.clone(), vec![mine_pub.clone()], SOFTWARE_OPS)
            .expect("still a candidate");
        std::fs::write(&path, mine.to_bytes()).expect("swap the operator's own key back in");
        let swapped = found.discard(DISCARD_UNRECORDED_KEY_PHRASE);
        assert!(
            matches!(
                &swapped,
                Err(SeErr::EnclaveKeyChangedUnderDiscard { shown, found, .. })
                    if *shown == se_fingerprint(&squatter_pub) && *found == se_fingerprint(&mine_pub)
            ),
            "{swapped:?}"
        );
        assert_eq!(
            software_pubkey(&path).expect("the swapped-in key survives"),
            mine_pub
        );

        let found = unrecorded_key_at(path.clone(), Vec::new(), SOFTWARE_OPS)
            .expect("nothing recorded makes every key at the path a candidate");
        found
            .discard(&format!("  {DISCARD_UNRECORDED_KEY_PHRASE}\n"))
            .expect("the exact phrase, however the terminal padded it, discards");
        assert!(matches!(
            unrecorded_key_at(path, Vec::new(), SOFTWARE_OPS),
            Err(SeErr::NoEnclaveKeyToDiscard { .. })
        ));
    }

    #[test]
    fn enclave_labels_have_one_unambiguous_file_spelling() {
        assert!(validate_label(SE_KEY_LABEL).is_ok());
        assert!(validate_label(SE_GRANT_KEY_LABEL).is_ok());
        for invalid in ["", "a_b", "../key", "key-name", "nul\0label"] {
            assert!(
                matches!(validate_label(invalid), Err(SeErr::InvalidLabel { .. })),
                "{invalid:?} must not alias an enclave blob"
            );
        }
    }
}
