//! Secure Enclave P-256 KEK: a Touch-ID-gated key whose ECDH unwraps the DEK.
//!
//! The private key is generated by CryptoKit's `SecureEnclave.P256.KeyAgreement`
//! (Swift shim in `swift/se_bridge.swift`), never leaves the enclave, and persists as
//! an opaque `dataRepresentation` blob in a 0600 file under the home dir — no keychain,
//! no entitlement, no provisioning profile. Each ECDH requires a live biometric.
//!
//! Enrollment computes `ECDH(eph_priv, se_pub)` on the host (`p256`); unlock computes the
//! mirror `ECDH(se_priv, eph_pub)` in the enclave. Standard P-256 ECDH is symmetric and
//! both sides encode the raw big-endian X-coordinate (32 bytes, no KDF), so they must
//! yield identical bytes. `hot_cheese se-selftest` proves that on real hardware.
//!
//! Alongside the KEK sits a second, independent enclave key: the **grant key**
//! (`SecureEnclave.P256.Signing`, blob `se_grant_<label>.blob`). It wraps nothing and
//! decrypts nothing. Its only job is [`grant_sign`]: a biometric-gated ECDSA signature over
//! SHA-256 of a caller-supplied message, so a signature under the pinned public key is
//! hardware-attested proof that a human approved exactly those bytes. Losing it costs
//! nothing but a re-run of `hot_cheese enroll grant`.
use crate::crypto::envelope::write_private_file;
use crate::mac::local_auth::LaContext;
use err_mac::create_err_with_impls;
use std::ffi::{c_char, c_void, CString};
use std::path::{Path, PathBuf};
use zeroize::{Zeroize, Zeroizing};

create_err_with_impls!(
    #[derive(Debug)]
    pub SeErr,
    Unavailable,
    ScreenLocked,
    KeyNotFound,
    BadPubKeyLen(usize),
    BadPeerPoint,
    SoftwareKey,
    TouchIdDenied,
    Ecdh,
    GrantSign,
    GrantSignatureInvalid,
    BadBlob,
    BufferTooSmall,
    Shim(i32),
    StdIo(std::io::Error)
    ;
    Create { code: i32 },
    AccessControl { code: i32 },
    BadSignatureLen { len: usize },
    GrantReuseWindowExceeded { elapsed_ms: u64, window_ms: u64 },
);

/// Raw P-256 ECDH result: the 32-byte field element (X-coordinate).
const P256_SHARED_LEN: usize = 32;
/// Uncompressed SEC1 point: `0x04 || X(32) || Y(32)`.
const SEC1_UNCOMPRESSED_LEN: usize = 65;
const SEC1_UNCOMPRESSED_TAG: u8 = 0x04;
/// Raw P-256 ECDSA signature: `r(32) || s(32)`, no DER wrapper.
const P256_SIGNATURE_LEN: usize = 64;
/// Upper bound for a `SecureEnclave.P256` `dataRepresentation` blob (~569 bytes observed).
const SE_BLOB_MAX: usize = 1024;

/// `errSecInteractionNotAllowed`: the SEP will not issue a `kSecAttrAccessibleWhenUnlocked`
/// key while the login session's screen is locked.
const ERR_SEC_INTERACTION_NOT_ALLOWED: i32 = -25308;

const HC_ERR_CREATE: i32 = -1;
const HC_ERR_ACCESS_CONTROL: i32 = -2;
const HC_ERR_BAD_BLOB: i32 = -3;
const HC_ERR_BAD_PEER: i32 = -4;
const HC_ERR_ECDH: i32 = -5;
const HC_ERR_SIGN: i32 = -6;
const HC_ERR_BUFFER_TOO_SMALL: i32 = -10;

/// The label under which every machine stores its device-bound Secure Enclave KEK key.
/// Shared by the CLI and the SSH bootstrap so they always reference the same key.
pub const SE_KEY_LABEL: &str = "hotcheese.se.kek.v1";

/// The label under which every machine stores its device-bound Secure Enclave grant key.
pub const SE_GRANT_KEY_LABEL: &str = "hotcheese.se.grant.v1";

/// Touch ID sheet text for the two throwaway-key ECDHs of [`selftest`].
const SELFTEST_REASON: &str = "Run the hot_cheese Secure Enclave self-test";

/// Touch ID sheet text for the single pre-evaluated context [`selftest`] reuses.
const SELFTEST_REUSE_REASON: &str =
    "Approve once for the hot_cheese Secure Enclave self-test (ECDH + grant signature)";

/// Payload [`selftest`] signs with the throwaway grant key and verifies host-side.
const SELFTEST_GRANT_MSG: &[u8] = b"hotcheese/se-grant-selftest/v1";

extern "C" {
    fn hc_se_available() -> i32;
    fn hc_se_create(out: *mut u8, cap: usize, out_len: *mut usize, detail: *mut i32) -> i32;
    fn hc_se_public_key(
        blob: *const u8,
        blob_len: usize,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_ecdh(
        blob: *const u8,
        blob_len: usize,
        peer: *const u8,
        peer_len: usize,
        la_ctx: *mut c_void,
        reason: *const c_char,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_sign_create(out: *mut u8, cap: usize, out_len: *mut usize, detail: *mut i32) -> i32;
    fn hc_se_sign_public_key(
        blob: *const u8,
        blob_len: usize,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
    fn hc_se_sign_grant(
        blob: *const u8,
        blob_len: usize,
        msg: *const u8,
        msg_len: usize,
        la_ctx: *mut c_void,
        reason: *const c_char,
        out: *mut u8,
        cap: usize,
        out_len: *mut usize,
    ) -> i32;
}

fn map_shim(code: i32) -> SeErr {
    match code {
        HC_ERR_BAD_BLOB => SeErr::BadBlob,
        HC_ERR_BAD_PEER => SeErr::BadPeerPoint,
        HC_ERR_ECDH => SeErr::Ecdh,
        HC_ERR_SIGN => SeErr::GrantSign,
        HC_ERR_BUFFER_TOO_SMALL => SeErr::BufferTooSmall,
        other => SeErr::Shim(other),
    }
}

/// Whether this machine has a usable Secure Enclave.
pub fn se_available() -> bool {
    unsafe { hc_se_available() == 1 }
}

/// Map a key label to a filesystem-safe stem shared by the SE-blob and demo-key schemes.
fn sanitize_label(label: &str) -> String {
    label
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// On-disk location of the Secure Enclave key blob for `label` (under the home dir).
fn se_blob_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("se_kek_{}.blob", sanitize_label(label)))
}

/// On-disk location of the Secure Enclave grant-signing key blob for `label`.
fn se_grant_blob_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("se_grant_{}.blob", sanitize_label(label)))
}

fn read_blob(path: &Path) -> Result<Vec<u8>, SeErr> {
    match std::fs::read(path) {
        Ok(b) => Ok(b),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Err(SeErr::KeyNotFound),
        Err(e) => Err(e.into()),
    }
}

/// Create (idempotently) this machine's Touch-ID-bound SE key under `label`. No Touch ID.
pub fn ensure_se_key(label: &str) -> Result<(), SeErr> {
    if software_enclave_enabled() {
        return ensure_software_key(label);
    }
    ensure_se_key_at(&se_blob_path(label))
}

/// Shim entry point that mints an enclave key and writes its `dataRepresentation`.
type ShimCreate = unsafe extern "C" fn(*mut u8, usize, *mut usize, *mut i32) -> i32;
/// Shim entry point that reloads a blob and writes the key's SEC1 public point.
type ShimPublicKey = unsafe extern "C" fn(*const u8, usize, *mut u8, usize, *mut usize) -> i32;

/// Mint an enclave key through `create` and persist its blob 0600 at `path`. No Touch ID.
fn create_blob_at(path: &Path, create: ShimCreate) -> Result<(), SeErr> {
    if !se_available() {
        return Err(SeErr::Unavailable);
    }
    let mut out = [0u8; SE_BLOB_MAX];
    let mut out_len: usize = 0;
    let mut detail: i32 = 0;
    let code = unsafe { create(out.as_mut_ptr(), out.len(), &mut out_len, &mut detail) };
    match code {
        0 => {}
        HC_ERR_CREATE if detail == ERR_SEC_INTERACTION_NOT_ALLOWED => {
            return Err(SeErr::ScreenLocked)
        }
        HC_ERR_CREATE => return Err(SeErr::Create { code: detail }),
        HC_ERR_ACCESS_CONTROL => return Err(SeErr::AccessControl { code: detail }),
        other => return Err(map_shim(other)),
    }
    write_private_file(path, &out[..out_len])?;
    Ok(())
}

fn ensure_se_key_at(path: &Path) -> Result<(), SeErr> {
    if path.exists() {
        return Ok(());
    }
    create_blob_at(path, hc_se_create)?;
    tracing::info!(path = %path.display(), "created Secure Enclave P-256 key");
    Ok(())
}

/// Export the SE public key as uncompressed SEC1 (`0x04 || X || Y`, 65 bytes). No Touch ID.
pub fn se_public_key(label: &str) -> Result<Vec<u8>, SeErr> {
    if software_enclave_enabled() {
        return software_pubkey(&software_key_path(label));
    }
    export_public_key(&se_blob_path(label), hc_se_public_key)
}

/// Reload the blob at `path` through `export` and return its 65-byte uncompressed SEC1
/// public point, rejecting anything that is not one. No Touch ID.
fn export_public_key(path: &Path, export: ShimPublicKey) -> Result<Vec<u8>, SeErr> {
    let blob = read_blob(path)?;
    let mut out = [0u8; SEC1_UNCOMPRESSED_LEN];
    let mut out_len: usize = 0;
    let code = unsafe {
        export(
            blob.as_ptr(),
            blob.len(),
            out.as_mut_ptr(),
            out.len(),
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != SEC1_UNCOMPRESSED_LEN || out[0] != SEC1_UNCOMPRESSED_TAG {
        return Err(SeErr::BadPubKeyLen(out_len));
    }
    Ok(out.to_vec())
}

/// Deterministic ECDH between the SE private key and `peer_pub_sec1` (65-byte SEC1).
/// Triggers Touch ID (reusing `auth`'s pre-evaluated context when present, which already
/// carries its own prompt text). `reason` names the key and operation on the Touch ID sheet
/// of a fresh prompt. Returns the 32-byte shared X-coordinate, zeroized on drop.
pub fn se_ecdh(
    label: &str,
    peer_pub_sec1: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<Zeroizing<[u8; 32]>, SeErr> {
    if software_enclave_enabled() {
        return software_se_ecdh(label, peer_pub_sec1, auth, reason);
    }
    if peer_pub_sec1.len() != SEC1_UNCOMPRESSED_LEN || peer_pub_sec1[0] != SEC1_UNCOMPRESSED_TAG {
        return Err(SeErr::BadPubKeyLen(peer_pub_sec1.len()));
    }
    if p256::PublicKey::from_sec1_bytes(peer_pub_sec1).is_err() {
        return Err(SeErr::BadPeerPoint);
    }
    let blob = read_blob(&se_blob_path(label))?;
    let la_ctx = match auth {
        Some(a) => a.as_raw_ptr(),
        None => std::ptr::null_mut(),
    };
    let reason_c = CString::new(reason).unwrap_or_default();
    let mut out = Zeroizing::new([0u8; P256_SHARED_LEN]);
    let mut out_len: usize = 0;
    let code = unsafe {
        hc_se_ecdh(
            blob.as_ptr(),
            blob.len(),
            peer_pub_sec1.as_ptr(),
            peer_pub_sec1.len(),
            la_ctx,
            reason_c.as_ptr(),
            out.as_mut_ptr(),
            P256_SHARED_LEN,
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != P256_SHARED_LEN {
        return Err(SeErr::Ecdh);
    }
    Ok(out)
}

/// Create (idempotently) this machine's Touch-ID-bound SE grant-signing key under `label`.
/// Wraps nothing and unwraps nothing, so losing it costs only a re-run. No Touch ID.
pub fn ensure_grant_key(label: &str) -> Result<(), SeErr> {
    if software_enclave_enabled() {
        return ensure_software_key_at(&software_grant_key_path(label));
    }
    let path = se_grant_blob_path(label);
    if path.exists() {
        return Ok(());
    }
    create_blob_at(&path, hc_se_sign_create)?;
    tracing::info!(path = %path.display(), "created Secure Enclave P-256 grant key");
    Ok(())
}

/// Export the grant key's public key as uncompressed SEC1 (65 bytes). No Touch ID.
pub fn grant_public_key(label: &str) -> Result<Vec<u8>, SeErr> {
    if software_enclave_enabled() {
        return software_pubkey(&software_grant_key_path(label));
    }
    export_public_key(&se_grant_blob_path(label), hc_se_sign_public_key)
}

/// ECDSA-sign SHA-256 of `msg` inside the enclave and return the raw `r || s` (64 bytes).
/// Triggers Touch ID (reusing `auth`'s pre-evaluated context when present); `reason` names
/// the operation on the sheet of a fresh prompt. The signature is public: it is proof that a
/// live human approved exactly `msg`, never a secret.
pub fn grant_sign(
    label: &str,
    msg: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<[u8; P256_SIGNATURE_LEN], SeErr> {
    if software_enclave_enabled() {
        return software_grant_sign(label, msg, auth, reason);
    }
    let blob = read_blob(&se_grant_blob_path(label))?;
    let la_ctx = match auth {
        Some(a) => a.as_raw_ptr(),
        None => std::ptr::null_mut(),
    };
    let reason_c = CString::new(reason).unwrap_or_default();
    let mut out = [0u8; P256_SIGNATURE_LEN];
    let mut out_len: usize = 0;
    let code = unsafe {
        hc_se_sign_grant(
            blob.as_ptr(),
            blob.len(),
            msg.as_ptr(),
            msg.len(),
            la_ctx,
            reason_c.as_ptr(),
            out.as_mut_ptr(),
            P256_SIGNATURE_LEN,
            &mut out_len,
        )
    };
    if code != 0 {
        return Err(map_shim(code));
    }
    if out_len != P256_SIGNATURE_LEN {
        return Err(SeErr::BadSignatureLen { len: out_len });
    }
    Ok(out)
}

/// Delete the SE key (rotation / uninstall). Idempotent: removing the blob file makes the
/// enclave key unrecoverable, since the blob is its only persistence.
pub fn delete_se_key(label: &str) -> Result<(), SeErr> {
    if software_enclave_enabled() {
        let _ = std::fs::remove_file(software_key_path(label));
        return Ok(());
    }
    match std::fs::remove_file(se_blob_path(label)) {
        Ok(()) => {
            tracing::info!(label = %label, "deleted Secure Enclave key");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}

/// Delete the SE grant key. Idempotent, and benign: nothing is wrapped under it, so the
/// operator recovers with `hot_cheese enroll grant` and a re-pin.
pub fn delete_grant_key(label: &str) -> Result<(), SeErr> {
    if software_enclave_enabled() {
        let _ = std::fs::remove_file(software_grant_key_path(label));
        return Ok(());
    }
    match std::fs::remove_file(se_grant_blob_path(label)) {
        Ok(()) => {
            tracing::info!(label = %label, "deleted Secure Enclave grant key");
            Ok(())
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}

/// True only when the insecure software-enclave demo backend is explicitly enabled. It
/// swaps the Secure Enclave for an extractable on-disk P-256 key gated by a Touch ID
/// prompt, reproducing the exact enroll/unlock/serve flow. NEVER for real keys.
pub fn software_enclave_enabled() -> bool {
    std::env::var_os("HOT_CHEESE_INSECURE_SOFTWARE_ENCLAVE").is_some()
}

/// On-disk location of the demo software key for `label`. Per-label so the throwaway
/// self-test key never shares a file with (and deletes) the real enrolled key.
fn software_key_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("software_enclave_{}.key", sanitize_label(label)))
}

/// On-disk location of the demo software GRANT key for `label`. Distinct from the demo KEK
/// file so the demo keeps the same two-independent-keys shape as the hardware path.
fn software_grant_key_path(label: &str) -> PathBuf {
    crate::config::home_dir().join(format!("software_grant_{}.key", sanitize_label(label)))
}

fn ensure_software_key(label: &str) -> Result<(), SeErr> {
    ensure_software_key_at(&software_key_path(label))
}

/// Create the demo software key if absent (idempotent).
fn ensure_software_key_at(path: &Path) -> Result<(), SeErr> {
    if path.exists() {
        return Ok(());
    }
    let sk = p256::SecretKey::random(&mut rand::rngs::OsRng);
    let mut raw = sk.to_bytes();
    write_private_file(path, &raw)?;
    raw.as_mut_slice().zeroize();
    tracing::warn!(
        path = %path.display(),
        "DEMO: created a SOFTWARE 'enclave' key ON DISK (extractable, NOT hardware-backed)"
    );
    Ok(())
}

/// Load the demo software key (32-byte P-256 scalar) from `path`. A missing file reads as
/// [`SeErr::KeyNotFound`], exactly as a missing enclave blob does, so the demo shows the
/// hardware path's "not enrolled" failures rather than a raw io error.
fn load_software_key_at(path: &Path) -> Result<p256::SecretKey, SeErr> {
    let bytes = read_blob(path)?;
    if bytes.len() != P256_SHARED_LEN {
        return Err(SeErr::SoftwareKey);
    }
    let field = p256::FieldBytes::clone_from_slice(&bytes);
    p256::SecretKey::from_bytes(&field).map_err(|_| SeErr::SoftwareKey)
}

/// Demo public key as uncompressed SEC1 (65 bytes).
fn software_pubkey(path: &Path) -> Result<Vec<u8>, SeErr> {
    let sk = load_software_key_at(path)?;
    Ok(sk.public_key().to_sec1_bytes().into_vec())
}

/// Demo ECDH: gate with a real Touch ID prompt (LAContext) carrying `reason`, then ECDH
/// against the software key. Same deterministic raw shared secret as the SE path.
fn software_se_ecdh(
    label: &str,
    peer_pub_sec1: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<Zeroizing<[u8; 32]>, SeErr> {
    tracing::warn!("DEMO software enclave: unlocking with an on-disk key (NOT hardware)");
    if auth.is_none()
        && !crate::mac::authorize_with_touch_id(&format!("{reason} (DEMO software enclave)"))
    {
        return Err(SeErr::TouchIdDenied);
    }
    let sk = load_software_key_at(&software_key_path(label))?;
    let peer = p256::PublicKey::from_sec1_bytes(peer_pub_sec1).map_err(|_| SeErr::BadPeerPoint)?;
    let shared = p256::ecdh::diffie_hellman(sk.to_nonzero_scalar(), peer.as_affine());
    let mut out = [0u8; 32];
    out.copy_from_slice(shared.raw_secret_bytes().as_slice());
    Ok(Zeroizing::new(out))
}

/// Demo grant signature: gate with a real Touch ID prompt carrying `reason`, then ECDSA-sign
/// SHA-256 of `msg` host-side. Same 64-byte `r || s` shape the enclave returns.
fn software_grant_sign(
    label: &str,
    msg: &[u8],
    auth: Option<&LaContext>,
    reason: &str,
) -> Result<[u8; P256_SIGNATURE_LEN], SeErr> {
    use p256::ecdsa::signature::Signer;

    tracing::warn!("DEMO software enclave: signing a grant with an on-disk key (NOT hardware)");
    if auth.is_none()
        && !crate::mac::authorize_with_touch_id(&format!("{reason} (DEMO software enclave)"))
    {
        return Err(SeErr::TouchIdDenied);
    }
    let sk = load_software_key_at(&software_grant_key_path(label))?;
    let signing = p256::ecdsa::SigningKey::from(&sk);
    let signature: p256::ecdsa::Signature = signing.sign(msg);
    let mut out = [0u8; P256_SIGNATURE_LEN];
    out.copy_from_slice(&signature.to_bytes());
    Ok(out)
}

/// Validate the Secure Enclave path end-to-end (requires SE hardware + Touch ID): create
/// throwaway KEK and grant keys under `label`, confirm their public-key shapes, confirm ECDH
/// is deterministic AND equals the host-side p256 ECDH used at enrollment, then confirm that
/// ONE pre-evaluated `LAContext` covers BOTH an enclave ECDH and an enclave ECDSA grant
/// signature that verifies host-side — the property per-payload grants are built on. Returns
/// the first failed property; both throwaway keys are deleted either way. Prompts Touch ID
/// three times: once per fresh ECDH, then once for the reused context. `label` MUST NOT be a
/// real deployment key.
pub fn selftest(label: &str) -> Result<(), SeErr> {
    use p256::ecdh::EphemeralSecret;
    use p256::ecdsa::signature::Verifier;
    use p256::elliptic_curve::sec1::ToEncodedPoint;
    use rand::rngs::OsRng;

    delete_se_key(label)?;
    delete_grant_key(label)?;
    ensure_se_key(label)?;
    ensure_se_key(label)?;
    ensure_grant_key(label)?;

    let result = (|| {
        let pk = se_public_key(label)?;
        if pk.len() != SEC1_UNCOMPRESSED_LEN || pk[0] != SEC1_UNCOMPRESSED_TAG {
            return Err(SeErr::BadPubKeyLen(pk.len()));
        }
        let eph = EphemeralSecret::random(&mut OsRng);
        let eph_pub = eph.public_key().to_encoded_point(false);
        let s1 = se_ecdh(label, eph_pub.as_bytes(), None, SELFTEST_REASON)?;
        let s2 = se_ecdh(label, eph_pub.as_bytes(), None, SELFTEST_REASON)?;
        if s1.as_slice() != s2.as_slice() {
            tracing::error!("SE ECDH is non-deterministic for a fixed peer");
            return Err(SeErr::Ecdh);
        }
        let se_pub = p256::PublicKey::from_sec1_bytes(&pk).map_err(|_| SeErr::BadPeerPoint)?;
        let host_shared = eph.diffie_hellman(&se_pub);
        if s1.as_slice() != host_shared.raw_secret_bytes().as_slice() {
            tracing::error!(
                "SE ECDH(se_priv, eph_pub) != host ECDH(eph_priv, se_pub) — SE-wrapped DEKs \
                 would be unrecoverable"
            );
            return Err(SeErr::Ecdh);
        }

        let grant_pk = grant_public_key(label)?;
        let verifying = p256::ecdsa::VerifyingKey::from_sec1_bytes(&grant_pk)
            .map_err(|_| SeErr::BadPubKeyLen(grant_pk.len()))?;
        let auth = LaContext::evaluate_biometric(SELFTEST_REUSE_REASON)?;
        let started = std::time::Instant::now();
        let reused = se_ecdh(label, eph_pub.as_bytes(), Some(&auth), SELFTEST_REASON)?;
        let raw = grant_sign(label, SELFTEST_GRANT_MSG, Some(&auth), SELFTEST_REASON)?;
        let elapsed_ms = started.elapsed().as_millis() as u64;

        if reused.as_slice() != s1.as_slice() {
            tracing::error!(
                "SE ECDH under the reused context differs from the freshly prompted one"
            );
            return Err(SeErr::Ecdh);
        }
        let signature =
            p256::ecdsa::Signature::from_slice(&raw).map_err(|_| SeErr::GrantSignatureInvalid)?;
        if verifying.verify(SELFTEST_GRANT_MSG, &signature).is_err() {
            tracing::error!(
                "enclave grant signature does not verify under the exported grant public key — \
                 an approval could never be proven"
            );
            return Err(SeErr::GrantSignatureInvalid);
        }
        let window_ms = (crate::mac::local_auth::TOUCH_ID_REUSE_SECS * 1000.0) as u64;
        if elapsed_ms > window_ms {
            tracing::error!(
                elapsed_ms,
                window_ms,
                "the enclave ECDH + grant signature did not both land inside the Touch ID reuse \
                 window, so one biometric per payload is NOT proven"
            );
            return Err(SeErr::GrantReuseWindowExceeded {
                elapsed_ms,
                window_ms,
            });
        }
        tracing::info!(
            elapsed_ms,
            window_ms,
            "one biometric covered both the enclave ECDH and the enclave grant signature"
        );
        Ok(())
    })();

    let _ = delete_se_key(label);
    let _ = delete_grant_key(label);
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    /// Proves the FFI create/persist/reload path on real SE hardware without a Touch ID prompt,
    /// skipping when the SEP refuses because the login session's screen is locked.
    #[test]
    fn se_key_creates_persists_and_exports_pubkey_without_touch_id() {
        if !se_available() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("hc_se_smoke_{}", std::process::id()));
        let path = dir.join("se_kek_smoke.blob");
        let _ = std::fs::remove_file(&path);

        match ensure_se_key_at(&path) {
            Err(SeErr::ScreenLocked) => return,
            other => other.expect("create SE key blob"),
        }
        assert!(path.exists(), "blob file must be written");
        let mode = std::fs::metadata(&path)
            .expect("stat blob")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "blob must be 0600");

        ensure_se_key_at(&path).expect("second create is a no-op");

        let pk = export_public_key(&path, hc_se_public_key).expect("export public key");
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        let pk2 = export_public_key(&path, hc_se_public_key).expect("reload + export public key");
        assert_eq!(pk, pk2, "reloaded key must yield the same public key");

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }

    /// Proves the grant key's create/persist/reload FFI path on real SE hardware without a
    /// Touch ID prompt, skipping when the SEP refuses because the screen is locked.
    #[test]
    fn grant_key_creates_persists_and_exports_pubkey_without_touch_id() {
        if !se_available() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("hc_grant_smoke_{}", std::process::id()));
        let path = dir.join("se_grant_smoke.blob");
        let _ = std::fs::remove_file(&path);

        match create_blob_at(&path, hc_se_sign_create) {
            Err(SeErr::ScreenLocked) => return,
            other => other.expect("create SE grant key blob"),
        }
        assert!(path.exists(), "blob file must be written");
        let mode = std::fs::metadata(&path)
            .expect("stat blob")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "blob must be 0600");

        let pk = export_public_key(&path, hc_se_sign_public_key).expect("export public key");
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        let pk2 =
            export_public_key(&path, hc_se_sign_public_key).expect("reload + export public key");
        assert_eq!(pk, pk2, "reloaded grant key must yield the same public key");

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }

    /// The DEMO software-enclave FILE backend persists, reloads identically, and exports the
    /// 65-byte uncompressed SEC1 public key that enroll/unlock depend on.
    #[test]
    fn software_demo_key_persists_and_exports_uncompressed_pubkey() {
        let path = std::env::temp_dir().join(format!("hc_sw_se_{}.key", std::process::id()));
        let _ = std::fs::remove_file(&path);
        ensure_software_key_at(&path).expect("create");
        ensure_software_key_at(&path).expect("idempotent second call");
        let sk1 = load_software_key_at(&path).expect("load");
        let sk2 = load_software_key_at(&path).expect("reload");
        assert_eq!(
            sk1.to_bytes(),
            sk2.to_bytes(),
            "persisted key must be stable"
        );
        let pk = sk1.public_key().to_sec1_bytes().into_vec();
        assert_eq!(pk.len(), SEC1_UNCOMPRESSED_LEN);
        assert_eq!(pk[0], SEC1_UNCOMPRESSED_TAG);
        let _ = std::fs::remove_file(&path);
    }

    /// Full SE round-trip (create, pubkey, deterministic + host-equivalent ECDH, one-biometric
    /// ECDH + grant signature, delete) via `selftest`, the same check `hot_cheese se-selftest`
    /// runs.
    #[test]
    #[ignore = "requires Secure Enclave hardware + Touch ID (prompts biometrics)"]
    fn se_key_lifecycle_and_deterministic_ecdh() {
        const TEST_LABEL: &str = "hotcheese.se.test_key";
        selftest(TEST_LABEL).expect("SE self-test");
        assert!(matches!(se_public_key(TEST_LABEL), Err(SeErr::KeyNotFound)));
        assert!(matches!(
            grant_public_key(TEST_LABEL),
            Err(SeErr::KeyNotFound)
        ));
    }
}
