[package]
name = "hc-console"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hc-bundle.workspace = true
hc-core.workspace = true
hc-daemon.workspace = true
hc-sign.workspace = true

alloy-primitives.workspace = true
bs58.workspace = true
crossterm.workspace = true
err_mac.workspace = true
hashbrown.workspace = true
hex.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
inquire.workspace = true
libc.workspace = true
parking_lot.workspace = true
pki-types.workspace = true
rand.workspace = true
rustls.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize.workspace = true

[dev-dependencies]
hc-core = { workspace = true, features = ["test-util"] }
hc-daemon = { workspace = true, features = ["test-util"] }
